### ISSUE TITLE
Feed the BOT with more content and users it can reply to

### ISSUE THREAD

**Issue by wigsnes** [wigsnes/TwitterContentReplyBot#1]
Read the CONTRIBUTION.md file on how to contribute to this project.

**Comment by may55** [comment]
@wigsnes  I would like to add some content.

**Comment by wigsnes** [comment]
Great! @may55. Go ahead and Fork the repository, make your contributions and create a pull request. If you have any problems or questions feel free to ask. This is a great introduction to open source. Glad you take a part in Hacktoberfest. 👍
