### ISSUE TITLE
Make a way to check if there are longer matching strings, and reply with the longest.

### ISSUE THREAD

**Issue by wigsnes** [wigsnes/TwitterContentReplyBot#14]
Now that the content file grows, we will eventually experience a tweet matching with multiple content elements. For now the best solution would probably be to reply with the the longest matching string, but other solutions might be interesting as to reply with what matches earliest in the tweet. Maybe a combination of both.

**Comment by gaurav-kay** [comment]
Hi!
I'd like to help.
I went through the code in twitter.py, I think this issue can be addressed by modifying the `tweetContains` method, can I go ahead with this?

**Comment by wigsnes** [comment]
@gaurav-kay yes, go ahead 😄
