### ISSUE TITLE
Add more users and automate the creation of mock data from all the users.

### ISSUE THREAD

**Issue by wigsnes** [wigsnes/TwitterContentReplyBot#17]
I expect 1000 of user, of the most followed twitter accounts.

The function you create will not work with the twitter API, as you might not have access to Twitter API keys. Start with just dummy data, and create a function that loops through all twitter followers and gets 5 recent tweets and saves them in a text file just like mock.json.

**Comment by ggrizzly** [comment]
I would like to work on this.

**Comment by wigsnes** [comment]
@ggrizzly Nice, Go ahead! 😄

**Comment by wigsnes** [comment]
@ggrizzly Hey dude, are you planning on finishing this task, if not I will do it myself today when I have time. I found about 500 twitter users and caught some bugs that I need to fix, so this wont take me long to include as well. Don't feel pressured not do finish in time, I will love to see your implementation as well 😄

**Comment by ggrizzly** [comment]
Hey, sorry, I got busy over the week / weekend, and totally spaced, so It's all good. Cheers! Sorry to string along.
