### ISSUE TITLE
Remove id and user from mock.json and set this in Mock twitter.py instead.

### ISSUE THREAD

**Issue by wigsnes** [wigsnes/TwitterContentReplyBot#7]
To make mock.json  better, and less cluttered, use the key to set user.name and set a random ID in twitter.py mock functions instead.

**Comment by GilSandler** [comment]
Hey,
I'm pretty new to open source contribution, but would like to try and tackle the issue :)

**Comment by SanthoshBala18** [comment]
Hey @GilSandler I am sorry I did not see your message before raising the request.

**Comment by GilSandler** [comment]
@SanthoshBala18 all good
